# Generated by Django 3.1.2 on 2020-10-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clinics', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='contact',
            field=models.CharField(max_length=45, verbose_name='Связаться с нами'),
        ),
    ]
