# Generated by Django 3.1.2 on 2020-11-06 16:24

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20201021_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='address',
        ),
        migrations.AddField(
            model_name='clinic',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
