# Generated by Django 3.1.2 on 2020-11-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
