# Generated by Django 3.1.2 on 2020-11-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20201113_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(max_length=125, null=True, unique=True),
        ),
    ]
