# Generated by Django 3.1.2 on 2020-11-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_clinic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(max_length=125, unique=True),
        ),
    ]
