# Generated by Django 3.1.2 on 2020-11-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20201114_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldepartment',
            name='slug',
            field=models.SlugField(max_length=125, null=True, unique=True),
        ),
    ]
