# Generated by Django 3.1.2 on 2020-11-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_medicaldepartment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldepartment',
            name='slug',
            field=models.SlugField(max_length=125, unique=True),
        ),
    ]
