# Generated by Django 3.1.2 on 2020-11-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_auto_20201114_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldepartment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-updated']},
        ),
    ]
