# Generated by Django 3.1.2 on 2020-11-15 14:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_auto_20201115_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Связаться с нами'),
        ),
    ]
