# Generated by Django 3.1.3 on 2020-11-22 14:23

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('image', models.ImageField(blank=True, upload_to='messages', verbose_name='Приложить фотографию(по желанию)')),
                ('message_subject', models.CharField(max_length=80, verbose_name='Тема сообщения')),
                ('message', models.TextField(verbose_name='Подробнее')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='user_account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('itn', models.CharField(blank=True, max_length=14, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('blood_type', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='user_account.clinic')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='user_account.profile')),
            ],
        ),
    ]
