# Generated by Django 3.1.2 on 2020-11-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0004_auto_20201115_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='messages', verbose_name='Приложить фотографию(по желанию)')),
                ('message_subject', models.CharField(max_length=80, verbose_name='Тема сообщения')),
                ('message', models.TextField(verbose_name='Подробнее')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='user_account.profile')),
            ],
        ),
    ]
