# Generated by Django 3.1.3 on 2020-11-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20201123_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
    ]
