# Generated by Django 3.1.2 on 2020-11-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20201115_1401'),
        ('user_account', '0006_auto_20201116_2228'),
        ('communication', '0003_auto_20201115_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('itn', models.CharField(blank=True, max_length=14)),
                ('birth_date', models.DateTimeField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('blood_type', models.CharField(blank=True, max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.clinic')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='user_account.profile')),
            ],
        ),
    ]
