# Generated by Django 3.1.3 on 2020-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_remove_message_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Обратная связь'),
        ),
    ]
