# Generated by Django 3.1.2 on 2020-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
    ]
