# Generated by Django 3.1.3 on 2020-11-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_appointment_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='answer',
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Обратная связь')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='communication.appointment')),
            ],
        ),
    ]
