# Generated by Django 3.1.3 on 2020-11-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_auto_20201125_1920'),
        ('communication', '0005_auto_20201124_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='user_account.doctor'),
        ),
    ]
