# Generated by Django 3.1.2 on 2020-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
