# Generated by Django 3.1.2 on 2020-11-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20201118_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
