# Generated by Django 3.1.2 on 2020-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_auto_20201120_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='itn',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
