# Generated by Django 3.1.2 on 2020-10-30 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='itn',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='ИНН должен состоять из 14 цифр', regex='^\\d{14}$')], verbose_name='ИНН'),
        ),
    ]
