# Generated by Django 3.1.3 on 2020-11-25 08:45

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_clinic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='42.858397010537054,434.56839323043823', max_length=63),
        ),
    ]
