# Generated by Django 3.1.3 on 2020-11-25 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20201125_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='doctor status'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='doctors/%Y/%m/%d', verbose_name='Аватар')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='user_account.clinic', verbose_name='Место работы')),
                ('specialization', models.ManyToManyField(related_name='doctors', to='user_account.MedicalDepartment', verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
