# Generated by Django 3.1.2 on 2020-11-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20201115_1401'),
        ('user_account', '0005_profile_favorite_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_clinic',
            field=models.ManyToManyField(blank=True, related_name='favorite_clinics', to='clinic.Clinic', verbose_name='Избранные клиники'),
        ),
    ]
